In [48]:
import numpy 

# QA-1

In [49]:
x= numpy.array([[1],[2],[3]])
y=numpy.array([[4],[5],[6]])
a=numpy.array([1,2,3])
b=numpy.array([4,5,6])
#print(numpy.subtract((numpy.multiply(2,x),y)))

In [50]:
z=numpy.multiply(2,x)

In [51]:
print(numpy.subtract(z,y))

[[-2]
 [-1]
 [ 0]]


# QA-2

In [52]:
import numpy.linalg

In [53]:
numpy.linalg.norm(x)

3.7416573867739413

# QA-3

In [54]:
x_hat = x / numpy.linalg.norm(x)

In [55]:
print (x_hat)

[[0.26726124]
 [0.53452248]
 [0.80178373]]


# QA-4

In [46]:
print(numpy.cos(x))

[[ 0.54030231]
 [-0.41614684]
 [-0.9899925 ]]


# QA-5

In [47]:
print(numpy.dot(a,b))

32


In [39]:
print(numpy.dot(b,a))

32


# QA-6

In [44]:
cosang = numpy.dot(a, b)
sinang = numpy.linalg.norm(numpy.cross(a, b))
print(numpy.arctan2(sinang, cosang))

0.22572612855273394


# QA-7

In [57]:
A=numpy.array([[1,0,0],[0,1,0],[0,0,1]])
v=numpy.random.randint(0,2)
print(numpy.cross(a,A[v]))

[ 0  3 -2]


# QA-8

In [58]:
print(numpy.cross(a,b))

[-3  6 -3]


In [59]:
print(numpy.cross(b,a))

[ 3 -6  3]


# QA-9

In [60]:
print(numpy.cross(a,b))

[-3  6 -3]


# QA-10

In [64]:
c=numpy.array([-1,1,3])
print(3*a-b)
print(c)

[-1  1  3]
[-1  1  3]


# QA-11

In [65]:
Z=(a.T)
Y=(b.T)
print(Z*b)
print(Y*a)

[ 4 10 18]
[ 4 10 18]


# QB-1

In [66]:
A1=numpy.array([[1,2,3],[4,-2,3],[0,5,-1]])
B1=numpy.array([[1,2,1],[2,1,-4],[3,-2,1]])
C1=numpy.array([[1,2,3],[4,5,6],[-1,1,3]])
print((2*A1)-B1)

[[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]


# QB-2

In [67]:
print(numpy.dot(A1,B1))

[[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]


In [68]:
print(numpy.dot(B1,A1))

[[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


# QB-3

In [69]:
AB_trans = numpy.dot(A1,B1)
print(AB_trans.T)

[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


In [74]:
B_trans = B1.T
A_trans = A1.T
print(numpy.dot(B_trans, A_trans))

[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


# QB-4

In [76]:
print(numpy.linalg.det(A1))

54.999999999999964


# QB-5

In [86]:
if((numpy.dot(A1[0],A1[1]) == 0) and (numpy.dot(A1[1],A1[2]) == 0) and (numpy.dot(A1[0],A1[2]) == 0)):
       print("A forms orthogonal set")
else:
    print("A doesnt form")
    
if((numpy.dot(C1[0],C1[1]) == 0) and (numpy.dot(C1[1],C1[2]) == 0) and (numpy.dot(C1[0],C1[2]) == 0)):
    print("C forms orthogonal set")
else:
    print("C doesnt form")

if((numpy.dot(B1[0],B1[1]) == 0) and (numpy.dot(B1[1],B1[2]) == 0) and (numpy.dot(B1[0],B1[2]) == 0)): 
    print("B forms orthogonal set")
else:
    print("B doesnt form")

A doesnt form
C doesnt form
B forms orthogonal set


# QB-6

In [77]:
print(numpy.linalg.det(C1))

7.494005416219837e-16


In [78]:
print(numpy.linalg.inv(A1))

[[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]


In [79]:
print(numpy.linalg.inv(B1))

[[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


# QC-1

In [88]:
A2=numpy.array([[1,2],[3,2]])
B2=numpy.array([[2,-2],[-2,5]])
eigen_values,eigen_vectors =numpy.linalg.eig(A2) 
print(eigen_values)
print(eigen_vectors)

[-1.  4.]
[[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


# QC-2

In [90]:
V_inv = numpy.linalg.inv(eigen_vectors)
D=(numpy.dot(V_inv,A2))
print(numpy.dot(D,eigen_vectors))

[[-1.0000000e+00 -4.4408921e-16]
 [ 0.0000000e+00  4.0000000e+00]]


In [93]:
print(numpy.dot(eigen_vectors[0],eigen_vectors[1]))

-0.038461538461538214


In [94]:
eigenvalues,eigenvectors =numpy.linalg.eig(B2) 
print(numpy.dot(eigenvectors[0],eigenvectors[1]))

0.0


In [95]:
print("Property of Eigenvectors of B: When multiplied with B, they yield the Eigenvectors")

Property of Eigenvectors of B: When multiplied with B, they yield the Eigenvectors
